version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cloudflow-db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cloudflow-server:
    build:
      context: .
      dockerfile: ./dockerfile
    container_name: cloudflow-server
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/cloudflow-db
    depends_on:
      - postgres

volumes:
  postgres_data:
